window.ecLinkInstallations = [
  ...[
    [2,"Capstone Community Church","Bulaon, Pampanga","Indoor Die-Cast · P3.91 · 2m × 5m"],
    [3,"Christ in You","Magalang, Pampanga","Indoor Die-Cast · P3.91 · 2m × 5m"],
    [4,"Doulous for Christ","Navotas","Indoor Die-Cast · P3.91 · 4m × 2.5m"],
    [5,"Christian Bible Church of Iba","Hagonoy, Bulacan","Indoor Die-Cast · P3.91 · 2m × 5m"],
    [6,"DPWH Bataan Overpass","Bataan","Outdoor Fixed Cabinet · P6 · 1.5m × 12m"],
    [7,"God's Beloved Church","Magalang, Pampanga","Indoor Die-Cast · P3.91 · 2m × 5m"],
    [8,"Hills of Glory International Christian Center","Philippines","Indoor Die-Cast · P3.91 · 2m × 5m"],
    [9,"Life in Christ Family Church","Xevera, Mabalacat","Indoor Die-Cast · P3.91 · 2m × 5m"],
    [10,"Lakas Angkan Ministries","CLSU, Nueva Ecija","Indoor Die-Cast · P3.91 · 2m × 5m"],
    [11,"JIL Guagua","Pampanga","Indoor Die-Cast · P3.91 · 2m × 5m"],
    [12,"YumChicken Signage","Bulacan","LED signage installation"],
    [13,"Pasay City Command Control & Information Center","Pasay City","Indoor Fixed Cabinet · P2.5 · 1.92m × 3.98m"],
    [14,"Light Church","Bajac-Bajac, Olongapo","Indoor Die-Cast · P3.91 · 2m × 5m"],
    [15,"Zyber Auto","Pampanga","Custom LED display"],
    [16,"Funnside Ningnangan","Caloocan","Outdoor Fixed · P6 · 3.84m × 3.07m"],
    [17,"San Juan City Disaster Risk Reduction & Management Office","San Juan City","Indoor Magnetic · 1.2m screen diameter"],
    [18,"Subic","Zambales","Outdoor Fixed · P6 · 7m × 3m"],
    [19,"Bomb Farm","Tarlac","Outdoor Die-Cast · P6 · 2.5m × 1.5m"],
    [20,"Subic Market","Zambales","Outdoor Fixed · P6 · 5m × 3m"],
    [21,"Azurro Hotel","Angeles City","Outdoor Die-Cast · P3 · 2m × 2m"],
    [22,"Grace Testament Church","Caloocan","Indoor Magnetic · P3 · 3m × 8m"],
    [23,"Christ Revelation Church","Mexico, Pampanga","Indoor Magnetic · P3.91 · 2m × 3m"],
    [24,"NEDA Region III","Central Luzon","Indoor Die-Cast · P3 · 1.5m × 3m"],
    [25,"The Breakthrough Community Church","Navotas","Indoor Magnetic · P3 · 2m × 5m"],
    [26,"Christ Revelation Church","Mexico, Pampanga","Indoor Magnetic · P3 · 2m × 3m"],
    [27,"New Life in Christ Church","Sta. Ana","Indoor Magnetic · P3 · 2m × 5m"],
    [28,"Christ Son of the Living God","Juliana, San Fernando","Indoor Magnetic · P3.91 · 2.5m × 4m"],
    [29,"Dragonstone","San Matias, Sto. Tomas","Outdoor Fixed Cabinet · P6 · 3.072m × 5.376m"],
    [30,"Life Giver Church Central","Quezon City","Indoor Magnetic · P3 · 3m × 6m"],
    [31,"LGU Banaue","Ifugao","Outdoor Fixed · P6 · 3.07m × 2.3m"],
    [32,"Zodiac Bar","Baguio","Indoor Magnetic · P3.91 · 2.5m × 1.5m"],
    [33,"Freedgeneration Church","Cagayan de Oro","Indoor Magnetic · P3.91 · 6.5m × 3m"],
    [34,"Life Point","Cagayan de Oro","Indoor Magnetic · P3.91 · 2m × 4m"],
    [35,"Victory Chapel Toril","Davao City","Indoor Magnetic · P3.91 · 3m × 1.5m"],
    [36,"Mawaque Christian Community Church","Mabalacat City","Indoor Magnetic · P3.91 · 2m × 2.5m"],
    [37,"World Changer Corner","Balanga, Bataan","Indoor Magnetic · P3.91 · 2m × 5m"],
    [38,"Malabag Community Bible Church","Silang, Cavite","Indoor Magnetic · P3.91 · 2m × 3m"],
    [39,"Municipal Hall Liloy","Zamboanga del Norte","Indoor Die-Cast · P3.91 · 3m × 6m"],
    [40,"Pilgrim Christian College Auditorium","Cagayan de Oro","Indoor Magnetic · P3.91 · 2.5m × 3m"],
    [41,"All By God's Grace","Bataan","Indoor Magnetic · P3.91 · 2m × 4m"],
    [42,"Virtual Playground","BGC, Taguig","Indoor Magnetic · P3.91 · 2m × 0.75m"],
    [43,"DepEd Opol","Misamis Oriental","Indoor Magnetic · P3.91 · 1.5m × 3m"],
    [44,"Joyful Life in Christ","Mabalacat, Pampanga","Indoor Magnetic · P3.91 · 2m × 5m"],
    [45,"Pabanlag Christian Church","Floridablanca, Pampanga","Indoor Magnetic · P3.91 · 2.5m × 4m"],
    [46,"Binalbagan Catholic College","Negros Oriental","Indoor Magnetic · P3.91 · 2.5m × 5m"],
    [47,"Tatay's Ener Restaurant","Misamis Oriental","Indoor Magnetic · P3.91 · 2m × 3.5m"],
    [48,"Jesus Our Tsidkenu Christian Fellowship","Guagua, Pampanga","Indoor Magnetic · P3.91 · 2m × 5m"],
    [49,"LLM Trading","Angeles City","Outdoor Fixed Cabinet · P3 · 2.3m × 2.3m"],
    [50,"General Santos City DepEd NEAP","General Santos City","Indoor Magnetic · P2.6 · 1.5m × 3.5m"],
    [51,"Consuming Fire Christian Church","Angeles City","Indoor Magnetic · P3.91 · 1.5m × 3m"],
    [52,"More Than Conqueror Christian Ministries","Porac, Pampanga","Indoor Magnetic · P3.91 · 2m × 5m"],
    [53,"Doulos Fishermall","Philippines","Indoor Die-Cast · P3.91 · 3m × 5m"],
    [54,"Christ Eminence Church","Navotas","Indoor Magnetic · P3.91 · 2m × 3m"],
    [55,"General Santos City DepEd NEAP","General Santos City","Indoor Magnetic · P2.6 · 1.5m × 3m"]
  ].map(([page, name, location, spec]) => ({ type: "led", image: `assets/installations/all/led-${String(page).padStart(2, "0")}.jpg`, label: "LED WALL", name, location, spec })),
  ...[
    [2,"Scholastica's Academy","Bacolod City","1 unit · 12 ft"],
    [3,"Our Lady of Guadalupe","Tugbok, Davao","2 units · 12 ft"],
    [4,"Scholastica's Academy","Bacolod City","1 unit · 12 ft"],
    [5,"Mary Help Christian School","Cebu","2 units · 24 ft"],
    [6,"SEAFDEC","Tigbauan, Iloilo","2 units · 12 ft"],
    [7,"Cotabato Regional and Medical Center","Cotabato","2 units · 24 ft"],
    [8,"Queen of Peace Parish Church","Cotabato","2 units · 11 ft"],
    [9,"Binalbagan Catholic College","Negros Occidental","2 units · 24 ft"],
    [10,"Toledo","Cebu","1 unit · 11 ft"],
    [11,"Surigao del Sur","Philippines","1 unit · 24 ft"],
    [12,"Cordoba","Cebu","1 unit · 24 ft"],
    [13,"Robredo Gymnasium","Naga City, Bohol","2 units · 24 ft"],
    [14,"Brgy. Campisao","Borongan City","2 units · 24 ft"],
    [15,"Lagao National High School","General Santos City","3 units · 12 ft"],
    [16,"Blue Palm Resort","North Cotabato","2 units · 24 ft"],
    [17,"Bayawan City","Negros Oriental","4 units · 12 ft"],
    [18,"St. Mary's College","Borongan, Eastern Samar","1 unit · 12 ft"],
    [19,"Digos National High School","Davao del Sur","2 units · 24 ft"],
    [20,"Sarangani","General Santos","2 units · 12 ft"],
    [21,"Tacloban","Leyte","3 units · 11 ft"],
    [22,"Ma-a","Davao","1 unit · 12 ft"],
    [23,"Jaro","Iloilo","1 unit · 11 ft"]
  ].map(([page, name, location, spec]) => ({ type: "fan", image: `assets/installations/all/fan-${String(page).padStart(2, "0")}.jpg`, label: "HVLS INDUSTRIAL FAN", name, location, spec }))
];
